### ISSUE TITLE
Disfonctionnement

### ISSUE THREAD

**Issue by Demon3rd** [3rd-KaTZe/SIOC#4]
salut Katze

suite release du EKPI, mise a jour de ta branche develop.
depuis plus de fonctionnement sur les Pit Helicos

Demon

**Comment by ghost** [comment]
Master(Pits + SIOC + Link) -> OK
Develop(Pits + SIOC + Link) -> NOK

**Comment by Demon3rd** [comment]
le disfonctionnement est confirmé malgré la mise à jour : 
@3rd-KaTZe : concernant le sioc.ini à la ligne 29 référence à "CONFIG_FILE=.\KaTZe_50-09.ssi" et non à katze.ssi"  quelque soit la branche.

@etcher3rd : concernant EKPI  je te transmet le log via MP sur le site de la 3rd, il doit je pense y avoir une erreur sur le fait qu'il ne trouve pas le sioc.ini ligne 258 du Log.

**Comment by 3rd-KaTZe** [comment]
A Priori réglé même si toujours problème chez certains de la 3rd.
Dans tous les cas pas une issue SIOC
